### ISSUE TITLE
Stray push method in Spread Operator post.

### ISSUE THREAD

**Issue by iifeoluwa** [wesbos/es6-articles#39]
Hi Wes,

I reached your [Spread Operator Introduction](https://github.com/wesbos/es6-articles/blob/master/28%20-%20Spread%20Operator%20Introduction.md) post from [here](https://github.com/mbeaudru/modern-js-cheatsheet#spread-operator-) because it was listed as an external resource. 

However, I encountered a stray `push` method in one of the code examples. I know it's not a big deal but beginners looking through might have a hard time going past that error.

It's right after the 9th paragraph.

```js
let pizzas =  [];
pizzas = pizzas.concat(featured);
pizzas = push('veg');
pizzas = pizzas.concat(specialty);
console.log(pizzas);
```

I believe the third line should be `pizzas.push('veg')`.  I can send in a PR for it if you'd like.

Regards.

**Comment by wesbos** [comment]
thanks! It's been fixed
