### ISSUE TITLE
Add warning about modifying array's contructor

### ISSUE THREAD

**Issue by DreadBoy** [wesbos/es6-articles#63]
I suggest you add a word of warning to article `54 - Extending Arrays with Classes for Custom Collection`. If you modify constructor signature of extended array, you will have bad time when trying to use `.map()`, `.slice()` or any other method that returns new instance of array. Javascript calls constructor each time it `.map()` is ran and that constructor is called with length of original array. Since you modified constructor signature, new copy of array won't be what you expected it to be.

**Comment by TinaHeiligers** [comment]
I'll tackle this one!

**Comment by TinaHeiligers** [comment]
There's some grammar that could use improvement in article 54, along with typos and spelling errors. @wesbos may I fix those in the same PR or should I open another one for those?

**Comment by wesbos** [comment]
@TinaHeiligers either will do! thank you :D
